#!/bin/sh
### General options
### -- set the job Name --
#BSUB -J bertclust
### -- ask for number of cores (default: 1) --
#BSUB -n 8

### -- set walltime limit: hh:mm --  maximum 24 hours for GPU-queues right now
#BSUB -W 12:00
# request 5GB of system-memory
#BSUB -R "rusage[mem=8GB]"
### -- set the email address --
# please uncomment the following line and put in your e-mail address,
# if you want to receive e-mail notifications on a non-default address
##BSUB -u your_email_address

### -- Specify the output and error file. %J is the job-id --
### -- -o and -e mean append, -oo and -eo mean overwrite --
#BSUB -o out/bert_%J.out
#BSUB -e out/bert_%J.err
# -- end of LSF options --

source $BLACKHOLE/dt/bin/activate

python balance_data_gpu.py

